version: '3.8'
services:
  dev_container:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 4200:4200

    command: tail -f /dev/null #keep container running
